name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.6
      - name: Build Gateway to jar
        run: mvn -f src/Gateway/pom.xml --batch-mode --update-snapshots clean package
      - name: Build Cars to jar
        run: mvn -f src/Cars/pom.xml --batch-mode --update-snapshots clean package
      - name: Build Rental to jar
        run: mvn -f src/Rental/pom.xml --batch-mode --update-snapshots clean package
      - name: Build Payment to jar
        run: mvn -f src/Payment/pom.xml --batch-mode --update-snapshots clean package

      - uses: docker/setup-buildx-action@v2
      - name: Build images
        timeout-minutes: 10
        run: docker compose build
        
      - name: Login
        uses: docker/login-action@v2
        with:
          username: sltn011
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push containers
        run: docker compose push

      - name: Deploy
        run: |
          kubectl config set-cluster rsoi --server="${{ secrets.YANDEX_URL }}" --insecure-skip-tls-verify=true
          kubectl config set-credentials sltn011 --token="${{ secrets.YANDEX_TOKEN }}"
          kubectl config set-context default --cluster=rsoi --user=sltn011
          kubectl config use-context default
          helm delete services && helm install services k8s/services-chart/
          sleep 45

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v3/postman/collection.json
          environment: v3/postman/environment.json
          delayRequest: 500
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 5
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"